/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.39.1
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { Src20Abi } from './Src20Abi';

export { Src20Abi__factory } from './factories/Src20Abi__factory';
